apiVersion: v1
kind: ReplicationController
metadata:
  name: "myrc1"
spec:
  replicas: 3
  selector:
    app: web
  template:
    metadata:
      name: "mypod1"
      labels:
        app: web
    spec:
      containers:
        - name: "myweb1"
          image: "cankush625/webpage"
