apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pyc-1
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: "192.168.43.21"
    path: "/data"
