apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pyc-1
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "D:\\Github Repositories\\Kubernetes-CKA-CKAD\\CKA\\PersistentVolume\\mystorage\\"
