apiVersion: v1
kind: Pod
metadata:
  name: "mypod1"
  labels:
    app: webapp
spec:
  containers:
    - name: "myweb1"
      image: "cankush625/webpage"
  tolerations:
    - effect: "NoSchedule"
      key: "my-type"
      value: "veryimp"
      operator: Equal
