apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mydb
spec:
  containers:
    - name: mydb
      image: mysql:5.6
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
